site_name: rakam_system docs
nav:
  - Home: index.md
  - Contributing: contributing.md
  - Getting Started: start.md
  - Quick Start: quick_start.md
  - Installation: installation.md
  - Tutorials: tutorials.md
  - Development Guid: development_guide.md
  - Components: components.md
  - Pipelines: pipelines.md
  - Gradio: gradio.md
  - Deployment & Operation: deployment.md
  - Templates: templates.md
theme: readthedocs
