name: Deploy site to Github pages

on:
  push:
    branches:
      - feature/docusaurus-app # Deploy whenever main is updated
  workflow_dispatch: # Allow manual deployments
permissions:
  contents: write

jobs:
  deploy-github-page:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js and yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "yarn"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Install dependencies for all workspaces
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      # Build the App
      - name: Build App
        env:
          DOCS_URL: https://rakam-ai.github.io/
          DOCS_BASEURL: /rakam-systems-docs/
        run: yarn run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # NOTE: GITHUB_TOKEN is a secret token that is automatically generated by GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # directory to deploy
